export { default as CartPage } from './CartPage';
export { default as CheckoutPage } from './CheckoutPage';
export { default as Home } from './HomePage';
export { default as OrderSuccessPage } from '../../components/user/OrderSuccess';
export { default as ProductDetailPage } from './ProductDetailPage';
export { default as StripePaymentPage } from './StripePaymentPage';
export { default as UserOrdersPage } from './UserOrdersPage';
export { default as UserProfilePage } from './UserProfilePage';
export { default as WishListPage } from './WishListPage';
